title: Общественный Спасательный Отряд Республики Хакасия
description: Официальный сайт Общественного Спасательного Отряда Республики Хакасия
baseurl: ""
url: ""

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

include:
  - _pages

sass:
  style: compressed

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
